from os import path

GO_FILE_TEMPLATE = """// THIS FILE IS AUTOGENERATED.
// For modifications regarding the default configuration, please edit the
// .tscrc.json file instead and use make to regenerate this file.

package config

// DefaultConfig is the default tscrc configuration
var DefaultConfig = []byte(`TSCRC`)
"""

jsonFileLocation = path.join(path.abspath(path.dirname(__file__)), '../config/.tscrc.json')
goFileLocation = path.join(path.abspath(path.dirname(__file__)), '../config/default.go')

if __name__ == '__main__':
  tscrc = open(jsonFileLocation, 'r').read()
  gofile = open(goFileLocation, 'w')
  gofile.write(GO_FILE_TEMPLATE.replace('TSCRC', tscrc))
  print('Generated default config!')
